const express = require('express')
require('dotenv').config()
const bodyParser = require('body-parser')
const apps = express()
const cors = require('cors')

const projectRouter = require('./src/routes/project')
const accountJobSeeker = require('./src/routes/account-job-seeker')
const accountRecruiter = require('./src/routes/account-recruiter')
const portofolioJobSeeker = require('./src/routes/portofolio_job_seeker')
const profileJobSeeker = require('./src/routes/profile_job_seeker')
const profileRecruiter = require('./src/routes/profile-recruiter')
const projectRecruiter = require('./src/routes/project-recruiter')
const skill = require('./src/routes/skill')
const workExpJobSeeker = require('./src/routes/work-exp-job-seeker')
const user = require('./src/routes/user')

apps.use(cors())
apps.use(bodyParser.urlencoded({ extended: true }))
apps.use('/project', projectRouter)
apps.use('/users', user)
apps.use('/account-job-seeker', accountJobSeeker)
apps.use('/account-recruiter', accountRecruiter)
apps.use('/portofolio-job-seeker', portofolioJobSeeker)
apps.use('/profile-job-seeker', profileJobSeeker)
apps.use('/profile-recruiter', profileRecruiter)
apps.use('/project-recruiter', projectRecruiter)
apps.use('/skill', skill)
apps.use('/work-exp-job-seeker', workExpJobSeeker)

apps.use((request, response, next) => {
  response.header('Access-Control-Allow-Origin', '*')
  response.header('Access-Control-Allow-Headers', 'Origin, X-Requested-With, Content-Type, Accept')
  next()
})
apps.listen(process.env.PORT, () => {
  console.log('Listening to port 8080!')
})
